apiVersion: v1
kind: Service
metadata:
  name: security-manager-api
  labels:
    app.kubernetes.io/name: security-manager-api
    app.kubernetes.io/instance: security-manager-api
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: security-manager-api
    app.kubernetes.io/instance: security-manager-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-manager-api
  labels:
    app.kubernetes.io/name: security-manager-api
    app.kubernetes.io/instance: security-manager-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: security-manager-api
      app.kubernetes.io/instance: security-manager-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: security-manager-api
        app.kubernetes.io/instance: security-manager-api
    spec:
      imagePullSecrets:
        - name: difesa-sipad-user
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - env:
          - name: DB_ARQ_USERNAME
            valueFrom:
              secretKeyRef:
                key: spring.datasource.username
                name: db-arq-secret
                optional: false
          - name: DB_ARQ_PASSWORD
            valueFrom:
              secretKeyRef:
                key: spring.datasource.password
                name: db-arq-secret
                optional: false
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                key: jwt.secret
                name: db-arq-secret
                optional: false
          envFrom:
            - configMapRef:
                name: arq-config-map
          name: security-manager-api
          securityContext:
            {}
          image: almaviva.jfrog.io/difesa-sipad-docker/transversal/security-manager-api:#{Build.BuildId}#
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8085
              protocol: TCP
          resources:
            {}
